#spring.application.name=JournalApp
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.uri=mongodb+srv://yash200411:yashingale2004@cluster0.5hplyxj.mongodb.net/?appName=Cluster0
#spring.data.mongodb.auto-index-creation=true